name: your_project_name
description: A new Flutter project

environment:
  sdk: ">=3.5.0 <4.0.0"  # You can adjust this to match your Flutter version

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.2.0  # Update
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.3  # Optional
  firebase_storage: ^12.1.2  # Optional

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

## Dependency overrides, if needed
#dependency_overrides:
#  firebase_core: ^2.10.0
#  cloud_firestore: ^4.10.0
