name: your_project_name
description: A new Flutter project

environment:
  sdk: ">=3.5.0 <4.0.0"  # Match your Flutter version

dependencies:
  flutter:
    sdk: flutter

  xml: ^6.1.0
  cloud_firestore: ^5.6.1       # Firebase Firestore for database operations
  firebase_core: ^3.3.0          # Core Firebase dependency
  firebase_auth: ^5.1.3          # Optional: for authentication, if needed
  firebase_storage: ^12.1.2      # Optional: for file storage, if needed
  fl_chart: ^0.68.0              # For creating charts, if required
  pie_chart: ^5.0.0
  tree_view_flutter: ^1.0.2
  #flutter_treeview: 1.0.7+1 # Check for the latest version
  flutter_treeview: ^1.0.6
  #flutter_decompose: ^1.0.0     # Dependency for pie charts
  webview_flutter: ^4.0.1  # Ensure this is the latest version

  syncfusion_flutter_charts: ^20.4.38
  syncfusion_flutter_core: ^20.4.38
  # For Syncfusion charts
  http: ^1.2.2
  syncfusion_flutter_gauges: ^20.4.38 # Latest stable HTTP package for API requests
#  google_api_availability: ^3.0.2 # For checking Google Play Services availability

  # Uncomment `url_launcher` if you need to open URLs.
#  url_launcher: ^6.3.1         # For opening URLs in a browser (optional)
  flutter_inappwebview: ^6.1.5


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/  # Add your image assets here, if any
